name: inotes
description: "This is the Upgraded Version of my previous Project iNotes App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  rename_app: ^1.6.2
  flutter_colorpicker: ^1.1.0
  flutter_slider_drawer: ^3.0.2
  flutter_slidable: ^3.1.2
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/inotes_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/inotes_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/